#!/usr/bin/env bash
# This is just an EXAMPLE.

echo 'Select a Preset:'
export meny_height=3
ret=($(epameny -1 \
       Ultrafast :: \
       Superfast :: \
       Veryfast  :: \
       Faster    :: \
       Fast      :: \
       Medium    :: \
       Slow      :: \
       Slower    :: \
       Veryslow  :: \
       Placebo   :: \
       Cancel    ::quit::)) || exit

index=$ret
value="${ret[@]:1}"

echo
echo "Selected '$value' (index $index)"
