#!/usr/bin/env bash
# This is just an EXAMPLE.

[[ -f 'styles/silly_02.inc' ]] && source 'styles/silly_02.inc'

echo 'Select a Preset: '
ret=($(epameny -1 \
       Ultrafast :: \
       Superfast :: \
       Veryfast  :: \
       Faster    :: \
       Fast      :: \
       Medium    :: \
       Slow      :: \
       Slower    :: \
       Veryslow  :: \
       Placebo   :: \
       Cancel    ::quit::)) || exit

index=$ret
value="${ret[@]:1}"

echo
echo "Selected '$value' (index $index)"
