#!/usr/bin/env bash
# This is an example for epameny.

[[ -f 'styles/style02.inc' ]] && source 'styles/style02.inc'

echo 'Select a Preset: '
data=($(meny_pick=-1 epameny \
        Ultrafast :: \
        Superfast :: \
        Veryfast  :: \
        Faster    :: \
        Fast      :: \
        Medium    :: \
        Slow      :: \
        Slower    :: \
        Veryslow  :: \
        Placebo   :: \
        Cancel    ::quit::)) || exit

index=$data
value="${data[@]:1}"

echo
echo "Selected '$value' (index $index)"
