#!/usr/bin/env bash
# This is an example for epameny.
# A 'grep' menu wrapper: show results & open the selection on the matched line.

mapfile -t < <(grep --line-number "$@" 2>/dev/null) || exit
(( ${#MAPFILE[@]} == 0 )) && exit

items=()
for line in "${MAPFILE[@]}"; do
    filename="${line/:*}"
    label=$(echo "$line" | tr -d '\\')

    # number=$(echo "$label" | tr -d: -f2)
    (( num_offs = ${#filename} + 1 ))
    tmp=${label:$num_offs}; number=${tmp/:*}

    items+=("$label" "$number $filename")
done

export meny_simple=0 \
       meny_trimmark=$'$' \
       meny_trimcol=100%
ret=($(epameny "${items[@]}")) || exit

index=${ret[0]}
number="${ret[1]}"
filename="${ret[@]:2}"

case "$VISUAL" in
    *vi*) "$VISUAL" -c ":$number" "$filename" ;;
    nano) "$VISUAL" -@ "$filename:$number" ;;
       *) less +gj"$number" "$filename" ;;
esac
