#!/usr/bin/env bash
# This is an example for epameny.
# Select a user and show their processes in a stupid way.

entries=()
for name in $(compgen -u | sort -d); do
    entries+=("$name" "ps --no-headers -u $name -o pid,cmd")
done

echo "Select a user to view processes for."
data=($(epameny "${entries[@]}")) || exit 0

entries=()
mapfile -t pinfo < <(${data[1]} ${data[@]:2})
for list in "${pinfo[@]}"; do
    entries+=("$list" "$(echo "$list" | awk '{print $1}')")
done

if (( ${#entries[@]} == 0 )); then
    echo "No processes found."
    exit 0
fi

echo "Select a process:"
data=($(epameny "${entries[@]}")) || exit 0
echo "Selected PID: ${data[1]}"
